s = set()
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))
n =input("enter a nuber here:")
s.add(int(n))

print(s)






















